### ISSUE TITLE
How to set track's input sub routing?

### ISSUE THREAD

**Issue by mangoleap** [leolabs/ableton-js#21]
I'm fiddling around with ableton-js and got to a point where I would like to edit a tracks's sub routing.

Let's say I want to set it to my audio interface's stereo channel 3&4.

I tried to get the setter to work:

`await track.set('current_input_sub_routing', 0)`

This raises the error

```
(node:8883) UnhandledPromiseRejectionWarning: Error: Python argument types in
    None.None(Track, int)
did not match C++ signature:
    None(TTrackPyHandle, TString)
```

Do you have a hint how the parameter should look like?

**Comment by leolabs** [comment]
Hey @mangoleap,
Thanks for your report! I think this is a type issue in my library. The parameter is supposed to be a string, so you'd pass `"0"` instead of `0`. I guess some inputs can have names, so that's why they are like that.

I'll push an update with better types which should fix this issue :)
