### ISSUE TITLE
Set pitch of clip

### ISSUE THREAD

**Issue by dir** [leolabs/ableton-js#34]
I'm trying to set the pitch of a clip.

Currently I've tried this to no avail:

```js
clip_slots.forEach(async (slot) => {
      if (slot.raw.is_playing === true) {
        let clip = await slot.get("clip");
        let name = await clip.get("name");
        let pitch = await clip.set("pitch", 20);
        console.log(track + ': ' + name);
      }
});
```

**Comment by dir** [comment]
Do you know where I could find general documentation on the things you can `set` and `get` from ableton.song, clips, etc?

**Comment by leolabs** [comment]
If you use TypeScript, you can make use of autocompletion to give you the properties you can get and set. Otherwise, you can take a look at the source files of ableton-js. For example, the clip properties you can set are defined [here](https://github.com/leolabs/ableton-js/blob/master/src/ns/clip.ts#L61-L64).

That being said, I noticed that the settable clip properties are incomplete in my codebase. If you want to change the clip's pitch, you can set `pitch_coarse` for semitones and `pitch_fine` for cents. 

I'll keep this issue open and will fix the types tomorrow.
